# ============================================================
# services/district_geo.py
# District-centroid lookup + nearest-mandi maths for the /bhav pages.
#
# The mandi feed carries no lat/long — only state/district/market strings —
# so "nearest mandi" is resolved at DISTRICT granularity: every mandi in a
# district shares its centroid. data/district_coords.json maps the feed's own
# "state|district" (lower-cased) to [lat, lon]; it is generated by geocoding
# each district once (scripts/geocode_districts) and read live here, cached by
# mtime so a refreshed file is picked up without a restart. A district we have
# no centroid for is simply skipped — the caller then falls back to its
# server-rendered highest-price panel, so the page degrades cleanly.
# ============================================================
import hashlib
import json
import logging
import math
import re
import time
import urllib.parse
import urllib.request
from pathlib import Path

logger = logging.getLogger("krishi.district_geo")

_COORDS_PATH = Path(__file__).resolve().parents[1] / "data" / "district_coords.json"

_coords: dict | None = None
_coords_mtime: float = -1.0

# Feed state spelling → geocoder-friendly name (only the odd ones).
_STATE_FIX = {"keralam": "Kerala", "chattisgarh": "Chhattisgarh",
              "pondicherry": "Puducherry", "nct of delhi": "Delhi"}

# data.gov district misspellings/variants the geocoder can't resolve as-is.
# Keyed by the raw feed district (lower-cased); only the geocoder QUERY is
# corrected — the lookup key stays the raw feed string, so nothing else shifts.
_DISTRICT_FIX = {
    "anakapally": "Anakapalli", "dr.b.r.a.konaseema": "Konaseema",
    "banaskanth": "Banaskantha", "panchmahals": "Panchmahal", "jhajar": "Jhajjar",
    "sirmore": "Sirmaur", "thirssur": "Thrissur", "shehdol": "Shahdol",
    "singroli": "Singrauli", "chattrapati sambhajinagar": "Aurangabad",
    "tsemenyu": "Tseminyu", "mayurbhanja": "Mayurbhanj", "tarntaran": "Tarn Taran",
    "swai madhopur": "Sawai Madhopur", "thiruchirappalli": "Tiruchirappalli",
    "thiruvellore": "Tiruvallur", "unokoti": "Unakoti", "farukhabad": "Farrukhabad",
    "kannuj": "Kannauj", "pillibhit": "Pilibhit", "dehradoon": "Dehradun",
    "nanital": "Nainital", "udhamsinghnagar": "Udham Singh Nagar",
    "sounth 24 parganas": "South 24 Parganas", "koria": "Koriya",
    "anupur": "Anuppur", "badwani": "Barwani", "amarawati": "Amravati",
    "ambedkarnagar": "Ambedkar Nagar", "khiri (lakhimpur)": "Lakhimpur Kheri",
}


def _norm_key(state: str, district: str) -> str:
    """Same key the generator writes — raw feed strings, stripped + lower-cased.
    Both sides read the same feed vocabulary, so exact match needs no fuzzing."""
    return f"{(state or '').strip().lower()}|{(district or '').strip().lower()}"


def load_coords() -> dict:
    """district_coords.json as a dict, reloaded only when the file changes."""
    global _coords, _coords_mtime
    try:
        m = _COORDS_PATH.stat().st_mtime
    except OSError:
        _coords = {}
        return _coords
    if _coords is None or m != _coords_mtime:
        try:
            _coords = json.loads(_COORDS_PATH.read_text(encoding="utf-8"))
        except Exception:
            _coords = {}
        _coords_mtime = m
    return _coords


def coord_for(state: str, district: str):
    """(lat, lon) for a feed (state, district), or None if unknown."""
    c = load_coords().get(_norm_key(state, district))
    if isinstance(c, (list, tuple)) and len(c) == 2:
        try:
            return float(c[0]), float(c[1])
        except (TypeError, ValueError):
            return None
    return None


def resolve_mandi_coords(state: str, district: str, market: str) -> tuple[float, float, bool] | None:
    """Resolve (lat, lon, is_exact) for a market in (state, district).

    Tries matching the market name against cached villages/towns in village_service.
    If matched, returns (lat, lon, True).
    Otherwise, falls back to the district centroid from district_coords.json with a
    deterministic small radial offset per market name so multiple mandis don't stack
    on a single pixel, returning (lat, lon, False).
    Returns None if the district itself cannot be geocoded.
    """
    if not state or not district:
        return None

    clean_mkt = re.sub(r'(?i)\b(apmc|mandi|grain market|sub yard|upaj mandi|sub market yard|market yard|main yard|yard)\b', '', market or '').strip()
    clean_mkt = re.sub(r'[\(\)\[\]\-]+', ' ', clean_mkt).strip()
    norm_mkt = re.sub(r'[\s._\-/()]+', '', clean_mkt).lower()

    # Try matching against village/town cache if available
    try:
        from backend.services import village_service
        s_slug = re.sub(r'[^a-z0-9]+', '-', (state or '').strip().lower()).strip('-')
        d_slug = re.sub(r'[^a-z0-9]+', '-', (district or '').strip().lower()).strip('-')
        villages = village_service.load(s_slug, d_slug)
        if villages and norm_mkt:
            for v in villages:
                v_name = v.get("name", "")
                v_hi = v.get("hi", "")
                v_slug = v.get("slug", "")
                if (norm_mkt == re.sub(r'[\s._\-/()]+', '', v_name).lower() or
                    (v_hi and norm_mkt == re.sub(r'[\s._\-/()]+', '', v_hi).lower()) or
                    (v_slug and v_slug == re.sub(r'[^a-z0-9]+', '-', clean_mkt.lower()).strip('-'))):
                    return round(float(v["lat"]), 5), round(float(v["lon"]), 5), True
    except Exception as e:
        logger.debug("village match error for %s/%s/%s: %s", state, district, market, e)

    # Fallback to district centroid
    centroid = coord_for(state, district)
    if not centroid:
        return None

    lat, lon = centroid
    if not market:
        return lat, lon, False

    # Deterministic radial offset (jitter) based on market name hash
    h = int(hashlib.md5(market.strip().lower().encode("utf-8")).hexdigest()[:6], 16)
    theta = (h % 360) * math.pi / 180.0
    radius_deg = 0.008 + ((h >> 9) % 20) * 0.001
    j_lat = round(lat + radius_deg * math.sin(theta), 5)
    j_lon = round(lon + radius_deg * math.cos(theta), 5)
    return j_lat, j_lon, False


def haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    r = 6371.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp = math.radians(lat2 - lat1)
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * r * math.asin(math.sqrt(a))


def nearest(rows, lat: float, lon: float, price_of, tie_km: float = 1.0):
    """The nearest mandi to (lat, lon) among `rows`.

    rows: dicts carrying 'state' and 'district'. price_of(row) -> number.
    Because same-district mandis share a centroid (identical distance), the
    "if two conflict, show the higher-priced one" rule is applied by picking
    the highest-priced mandi among all within `tie_km` of the closest.
    Returns (row, distance_km) or None when no row has a known centroid.
    """
    cand = []
    for r in rows:
        c = coord_for(r.get("state"), r.get("district"))
        if not c:
            continue
        cand.append((haversine_km(lat, lon, c[0], c[1]), r))
    if not cand:
        return None
    d_min = min(d for d, _ in cand)
    tied = [(d, r) for d, r in cand if d <= d_min + tie_km]
    d, row = max(tied, key=lambda dr: price_of(dr[1]) or 0)
    return row, d


# ── automatic backfill ──────────────────────────────────────
# Keeps district_coords.json complete without any manual step: after each daily
# mandi fetch, districts newly present in the snapshot but missing a centroid
# are geocoded once (free OSM/Nominatim, 1 req/sec) and written back. Bounded
# per run so a burst of new districts fills over a few runs rather than one long
# blocking pass. Runs inside the fetch worker thread, so the blocking calls
# never touch the event loop.
def _clean_district(d: str) -> str:
    d = (d or "").strip()
    fixed = _DISTRICT_FIX.get(d.lower())
    if fixed:
        return fixed
    return d.split("(")[0].strip() if "(" in d else d   # "Kozhikode(Calicut)" → "Kozhikode"


def _clean_state(s: str) -> str:
    s = (s or "").strip()
    return _STATE_FIX.get(s.lower(), s)


def _in_state(item: dict, st: str) -> bool:
    """Guards against a same-named place in the WRONG state: the result is
    accepted only if the feed's state name appears in its address/display name.
    (e.g. feed 'Ambedkarnagar' has no UP match, but a bare query lands on an
    'Ambedkar Nagar' locality in Tamil Nadu — rejected here.)"""
    st_l = (st or "").strip().lower()
    if not st_l:
        return True
    addr = item.get("address") or {}
    hay = f"{addr.get('state', '')} {item.get('display_name', '')}".lower()
    return st_l in hay


def _geocode_one(state: str, district: str):
    ds, st = _clean_district(district), _clean_state(state)
    # State-scoped queries only — never a bare "{district}, India" (that's what
    # sends a wrong-state match). Each candidate is state-validated before use.
    for q in (f"{ds}, {st}, India", f"{ds} district, {st}, India"):
        url = "https://nominatim.openstreetmap.org/search?" + urllib.parse.urlencode(
            {"q": q, "format": "json", "limit": 5, "countrycodes": "in", "addressdetails": 1})
        try:
            req = urllib.request.Request(
                url, headers={"User-Agent": "krashimitra/1.0 (district-centroids)"})
            with urllib.request.urlopen(req, timeout=20) as resp:
                data = json.load(resp)
            for item in data:
                if _in_state(item, st):
                    return round(float(item["lat"]), 5), round(float(item["lon"]), 5)
        except Exception as e:
            logger.warning("geocode error for %s/%s: %s", state, district, e)
        time.sleep(1.1)
    return None


def _save(coords: dict) -> None:
    global _coords, _coords_mtime
    tmp = _COORDS_PATH.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(coords, ensure_ascii=False, indent=0), encoding="utf-8")
    tmp.replace(_COORDS_PATH)
    _coords = coords
    try:
        _coords_mtime = _COORDS_PATH.stat().st_mtime
    except OSError:
        _coords_mtime = -1.0


def backfill_missing(max_new: int = 40) -> int:
    """Geocode up to `max_new` feed districts that have no centroid yet. Returns
    how many were added. Best-effort: any failure leaves the file untouched."""
    from backend.database.db import SessionLocal, MandiPrice
    db = SessionLocal()
    try:
        pairs = db.query(MandiPrice.state, MandiPrice.district).distinct().all()
    finally:
        db.close()

    coords = dict(load_coords())
    missing = [(s, d) for s, d in pairs
               if s and d and _norm_key(s, d) not in coords]
    if not missing:
        return 0

    added = 0
    for s, d in missing[:max_new]:
        r = _geocode_one(s, d)
        if r:
            coords[_norm_key(s, d)] = list(r)
            added += 1
    if added:
        _save(coords)
        logger.info("district_geo: geocoded %d new district(s) (%d still missing)",
                    added, len(missing) - added)
    return added
