// KrashiMitra News Hub - Master Articles & News Dataset (55+ Real Agricultural Stories)
window.KRASHI_NEWS_ARTICLES = [
  {
    id: 'news-lead',
    slug: 'ganna-pricing-analytics-up',
    title: 'गन्ने का मूल्य विश्लेषण 2026: SAP, FRP व चीनी मिलों के नए भुगतान नियम',
    excerpt: 'उत्तर प्रदेश, महाराष्ट्र व हरियाणा में गन्ने की नई खरीद दर, रिकवरी दर और चीनी मिलों द्वारा 14 दिनों में अनिवार्य भुगतान के नवीनतम सरकारी दिशा-निर्देश।',
    category: 'mandi',
    catLabel: 'मंडी बुलेटिन',
    time: 'आज ताज़ा',
    readTime: '4 मिनट',
    image: 'images/articles/ganna-pricing-analytics-up-card.webp',
    link: 'articles/ganna-pricing-analytics-up'
  },
  {
    id: 'news-1',
    slug: 'gehuu-price-analytic-up',
    title: 'गेहूं MSP व मंडी दर 2026: इस सीज़न में बिक्री का सबसे सही समय कब?',
    excerpt: 'मंडियों में गेहूं के ताज़ा आवक रुझान, सरकारी खरीद केंद्रों पर रजिस्ट्रेशन और व्यापारियों के भाव का सम्पूर्ण तुलनात्मक विश्लेषण।',
    category: 'mandi',
    catLabel: 'मंडी विश्लेषण',
    time: 'आज ताज़ा',
    readTime: '5 मिनट',
    image: 'images/articles/gehuu-price-analytic-up-card.webp',
    link: 'articles/gehuu-price-analytic-up'
  },
  {
    id: 'news-2',
    slug: 'pm-kusum-solar-pump-yojana',
    title: 'पीएम कुसुम सोलर पंप योजना: 60% सब्सिडी के साथ खेत में लगाएं सोलर पंप',
    excerpt: 'बिजली कटौती और भारी डीज़ल खर्च से मुक्ति। सोलर पंप योजना के लिए ऑनलाइन आवेदन प्रक्रिया, पात्रता और आवश्यक दस्तावेज।',
    category: 'yojana',
    catLabel: 'सरकारी योजना',
    time: 'आज',
    readTime: '6 मिनट',
    image: 'images/articles/pm-kusum-solar-pump-yojana-card.webp',
    link: 'articles/pm-kusum-solar-pump-yojana'
  },
  {
    id: 'news-3',
    slug: 'karnataka-monsoon',
    title: 'मानसून व मौसम पूर्वानुमान 2026: बारिश की स्थिति और खरीफ/रबी बुवाई गाइड',
    excerpt: 'मौसम विभाग का नया पूर्वानुमान — बारिश की संभावना, वर्षा जल संचयन और प्रमुख फसलों की सुरक्षा के लिए व्यावहारिक कृषि सलाह।',
    category: 'weather',
    catLabel: 'मौसम अलर्ट',
    time: 'आज',
    readTime: '4 मिनट',
    image: 'images/articles/karnataka-monsoon-card.webp',
    link: 'articles/karnataka-monsoon'
  },
  {
    id: 'news-4',
    slug: 'urea-guide-up',
    title: 'यूरिया व DAP की सही मात्रा: फसलों में खाद का सही समय और सरकारी सब्सिडी दरें',
    excerpt: 'मिट्टी की उर्वरता बढ़ाने और लागत घटाने के लिए नैनो यूरिया व संतुलित उर्वरक प्रबंधन की वैज्ञानिक गाइड।',
    category: 'khad',
    catLabel: 'उर्वरक सलाह',
    time: 'कल',
    readTime: '4 मिनट',
    image: 'images/articles/urea-guide-up-card.webp',
    link: 'articles/urea-guide-up'
  },
  {
    id: 'news-5',
    slug: 'pm-fasal-bima-yojana-2026',
    title: 'प्रधानमंत्री फसल बीमा योजना 2026: ओलावृष्टि व बेमौसम बारिश से नुकसान की भरपाई',
    excerpt: 'प्राकृतिक आपदा के 72 घंटे के भीतर नुकसान की सूचना दर्ज करने की ऑनलाइन व ऑफलाइन प्रक्रिया और टोल-फ्री हेल्पलाइन।',
    category: 'yojana',
    catLabel: 'सरकारी योजना',
    time: 'कल',
    readTime: '5 मिनट',
    image: 'images/articles/pm-fasal-bima-yojana-2026-card.webp',
    link: 'articles/pm-fasal-bima-yojana-2026'
  },
  {
    id: 'news-6',
    slug: 'garlic-farming-guide',
    title: 'लहसुन की जी-2 व रियावन वैरायटी: रिकॉर्ड मंडी भाव व निर्यात मांग',
    excerpt: 'मंदसौर व नीमच मंडी में लहसुन के ऐतिहासिक भाव। भंडारण की सही विधि और रोग नियंत्रण से किसान कमा रहे मोटा मुनाफा।',
    category: 'mandi',
    catLabel: 'मंडी दर',
    time: '2 दिन पहले',
    readTime: '4 मिनट',
    image: 'images/articles/garlic-farming-guide-card.webp',
    link: 'articles/garlic-farming-guide'
  },
  {
    id: 'news-7',
    slug: 'sarso-mahu-chepa',
    title: 'सरसों में माहू और चेपा कीट का देसी उपचार — बिना महंगे कीटनाशक के समाधान',
    excerpt: 'नीम का तेल और जैविक स्प्रे से कीटों का तुरंत सफाया। तेल प्रतिशत बढ़ाने के लिए सल्फर का संतुलित उपयोग।',
    category: 'crop',
    catLabel: 'कीट नियंत्रण',
    time: '2 दिन पहले',
    readTime: '3 मिनट',
    image: 'images/articles/sarso-mahu-chepa-card.webp',
    link: 'articles/sarso-mahu-chepa'
  },
  {
    id: 'news-8',
    slug: 'PM-kisan-samman-nidhi',
    title: 'पीएम किसान सम्मान निधि: 19वीं किस्त जारी, ₹2000 खाते में पाने के लिए e-KYC अनिवार्य',
    excerpt: 'पीएम किसान पोर्टल पर आधार लिंकिंग, लैंड सीडिंग और बैंक डीबीटी स्टेटस चेक करने का आसान तरीका।',
    category: 'yojana',
    catLabel: 'सरकारी योजना',
    time: '3 दिन पहले',
    readTime: '5 मिनट',
    image: 'images/articles/PM-kisan-samman-nidhi-card.webp',
    link: 'articles/PM-kisan-samman-nidhi'
  },
  {
    id: 'news-9',
    slug: 'sahjan-munga-ki-kheti',
    title: 'सहजन (मोरिंगा) की व्यावसायिक खेती: कम पानी में लाखों की कमाई का नया विकल्प',
    excerpt: 'सुपरफूड मोरिंगा की मांग देश-विदेश में तेजी से बढ़ रही है। छंटाई की तकनीक, पत्तियों का पाउडर और फली बिक्री से बंपर मुनाफा।',
    category: 'tech',
    catLabel: 'आधुनिक खेती',
    time: '3 दिन पहले',
    readTime: '5 मिनट',
    image: 'images/articles/sahjan-munga-ki-kheti-card.webp',
    link: 'articles/sahjan-munga-ki-kheti'
  },
  {
    id: 'news-10',
    slug: 'kisan-credit-card',
    title: 'किसान क्रेडिट कार्ड (KCC): 4% ब्याज पर ₹3 लाख तक का लोन, बनवाने की आसान प्रक्रिया',
    excerpt: 'किसानों को साहूकारों के चंगुल से बचाने के लिए कम ब्याज पर फसली ऋण। आवेदन फॉर्म, बैंक नियम और नवीनीकरण का पूरा विवरण।',
    category: 'yojana',
    catLabel: 'बैंक योजना',
    time: '4 दिन पहले',
    readTime: '6 मिनट',
    image: 'images/articles/kisan-credit-card-card.webp',
    link: 'articles/kisan-credit-card'
  },
  {
    id: 'news-11',
    slug: 'krishi-yantra-subsidy',
    title: 'कृषि यंत्र सब्सिडी 2026: ट्रैक्टर, रोटावेटर व थ्रेशर पर 40-50% तक सरकारी छूट',
    excerpt: 'SMAM योजना के तहत कृषि यंत्रों पर अनुदान के लिए ऑनलाइन टोकन व आवेदन पोर्टल की संपूर्ण जानकारी।',
    category: 'yojana',
    catLabel: 'यंत्र सब्सिडी',
    time: '4 दिन पहले',
    readTime: '5 मिनट',
    image: 'images/articles/krishi-yantra-subsidy-card.webp',
    link: 'articles/krishi-yantra-subsidy'
  },
  {
    id: 'news-12',
    slug: 'nano-urea-nano-dap',
    title: 'नैनो यूरिया व नैनो DAP: 1 बोतल बोरी जितने असरदार, जानें छिड़काव का सही समय',
    excerpt: 'इफ्को की तरल नैनो तकनीक से खाद की खपत और ढुलाई का खर्च 80% कम हुआ। पत्तों पर सीधे अवशोषण से फसल की हरियाली में बढ़ोतरी।',
    category: 'khad',
    catLabel: 'नैनो उर्वरक',
    time: '5 दिन पहले',
    readTime: '4 मिनट',
    image: 'images/articles/nano-urea-nano-dap-card.webp',
    link: 'articles/nano-urea-nano-dap'
  },
  {
    id: 'news-13',
    slug: 'gehun-unnat-kheti',
    title: 'गेहूं की उन्नत किस्में DBW 303 व DBW 327: प्रति एकड़ 28-30 क्विंटल तक पैदावार',
    excerpt: 'गर्मी सहनशील नई किस्मों की बुवाई, सीआरआई अवस्था में पहली सिंचाई और खरपतवार प्रबंधन की वैज्ञानिक विधि।',
    category: 'crop',
    catLabel: 'फसल गाइड',
    time: '5 दिन पहले',
    readTime: '5 मिनट',
    image: 'images/articles/gehun-unnat-kheti-card.webp',
    link: 'articles/gehun-unnat-kheti'
  },
  {
    id: 'news-14',
    slug: 'dairy-farming-doodh-utpadan',
    title: 'डेयरी फार्मिंग से दैनिक आमदनी: दुधारू पशुओं के आहार में साइलेज और मिनरल मिक्सचर',
    excerpt: 'प्रति दिन दूध उत्पादन बढ़ाने के लिए संतुलित पशुआहार, हरा चारा संरक्षण और डेयरी शेड का वैज्ञानिक मॉडल।',
    category: 'pashu',
    catLabel: 'डेयरी फार्मिंग',
    time: '6 दिन पहले',
    readTime: '6 मिनट',
    image: 'images/articles/dairy-farming-doodh-utpadan-card.webp',
    link: 'articles/dairy-farming-doodh-utpadan'
  },
  {
    id: 'news-15',
    slug: 'bakri-palan-guide',
    title: 'बकरी पालन: बरबरी व सिरोही नस्ल से कम लागत में तगड़ा मुनाफा, 50% NLM सब्सिडी',
    excerpt: 'छोटे व सीमांत किसानों के लिए एटीएम मशीन कही जाने वाली बकरी पालन परियोजना। बाड़ा निर्माण व टीकाकरण कैलेंडर।',
    category: 'pashu',
    catLabel: 'पशुपालन',
    time: '6 दिन पहले',
    readTime: '5 मिनट',
    image: 'images/articles/bakri-palan-guide-card.webp',
    link: 'articles/bakri-palan-guide'
  },
  {
    id: 'news-16',
    slug: 'pashu-lumpy-skin-rog',
    title: 'लंपी स्किन रोग (LSD) से बचाव: पशुओं में गाँठ दिखने पर तुरंत अपनाएं ये उपाय',
    excerpt: 'गोटपॉक्स वैक्सीन लगवाना और नीम की पत्तियों के धूएं से मक्खी-मच्छर नियंत्रण। पशुपालकों के लिए टोल फ्री नंबर 1962।',
    category: 'pashu',
    catLabel: 'पशु स्वास्थ्य',
    time: '1 हफ्ता पहले',
    readTime: '4 मिनट',
    image: 'images/articles/pashu-lumpy-skin-rog-card.webp',
    link: 'articles/pashu-lumpy-skin-rog'
  },
  {
    id: 'news-17',
    slug: 'chana-ki-kheti',
    title: 'चने की खेती: उकठा (विल्ट) रोग से बचाव और फली छेदक कीट पर नियंत्रण की दवाएं',
    excerpt: 'ट्राइकोडर्मा से बीज उपचार और काबुली व देशी चने में फूल आने के समय फवारणी का सटीक कार्यक्रम।',
    category: 'crop',
    catLabel: 'दलहन खेती',
    time: '1 हफ्ता पहले',
    readTime: '5 मिनट',
    image: 'images/articles/chana-ki-kheti-card.webp',
    link: 'articles/chana-ki-kheti'
  },
  {
    id: 'news-18',
    slug: 'pyaj-kharif-kheti-bhandaran',
    title: 'प्याज की खेती व भंडारण: सड़ांध और वजन घटने से बचाने के लिए आधुनिक कांदा चाल',
    excerpt: 'नासिक व इंदौर मंडियों में प्याज भाव के उतार-चढ़ाव से निपटने के लिए हवादार भंडारण कक्ष बनाने पर सरकारी अनुदान।',
    category: 'mandi',
    catLabel: 'सब्जी भंडारण',
    time: '1 हफ्ता पहले',
    readTime: '5 मिनट',
    image: 'images/articles/pyaj-kharif-kheti-bhandaran-card.webp',
    link: 'articles/pyaj-kharif-kheti-bhandaran'
  },
  {
    id: 'news-19',
    slug: 'mitti-jaanch-soil-health-card',
    title: 'मृदा स्वास्थ्य कार्ड (Soil Health Card): मिट्टी की जांच कराकर खाद की लागत में 30% बचत',
    excerpt: 'खेत से मिट्टी का सही नमूना लेने की 5 सावधानियां। नाइट्रोजन, फास्फोरस व पोटाश की संतुलित खुराक से जमीन को बचाएं।',
    category: 'khad',
    catLabel: 'मिट्टी परीक्षण',
    time: '1 हफ्ता पहले',
    readTime: '4 मिनट',
    image: 'images/articles/mitti-jaanch-soil-health-card-card.webp',
    link: 'articles/mitti-jaanch-soil-health-card'
  },
  {
    id: 'news-20',
    slug: 'mushroom-ki-kheti',
    title: 'मशरूम उत्पादन: एक छोटे कमरे से हर महीने ₹25,000 की कमाई, ऑयस्टर व बटन मशरूम',
    excerpt: 'बिना जमीन वाले युवाओं और महिलाओं के लिए वरदान। गेहूं के भूसे का उपचार, स्पॉन (बीज) मिलाना और बिक्री केंद्र।',
    category: 'tech',
    catLabel: 'कृषि व्यवसाय',
    time: '1 हफ्ता पहले',
    readTime: '5 मिनट',
    image: 'images/articles/mushroom-ki-kheti-card.webp',
    link: 'articles/mushroom-ki-kheti'
  },
  {
    id: 'news-21',
    slug: 'pmksy-drip-sinchai-subsidy',
    title: 'ड्रिप व स्प्रिंकलर सिंचाई सब्सिडी: 55% अनुदान के साथ पानी व बिजली दोनों की बचत',
    excerpt: 'प्रति बूंद अधिक फसल (Per Drop More Crop) अभियान के अंतर्गत सूक्ष्म सिंचाई संयंत्र स्थापित करने के नियम।',
    category: 'yojana',
    catLabel: 'सिंचाई योजना',
    time: '1 हफ्ता पहले',
    readTime: '5 मिनट',
    image: 'images/articles/pmksy-drip-sinchai-subsidy-card.webp',
    link: 'articles/pmksy-drip-sinchai-subsidy'
  },
  {
    id: 'news-22',
    slug: 'enam-online-fasal-bechna',
    title: 'e-NAM पोर्टल पर घर बैठे फसल बेचें: देश भर की 1300+ मंडियों से सीधे भाव पाएं',
    excerpt: 'मध्यस्थों के कमीशन से मुक्ति। अपनी उपज का ऑनलाइन सैंपल टेस्ट कराएं और सीधे बैंक खाते में भुगतान प्राप्त करें।',
    category: 'mandi',
    catLabel: 'ई-मंडी',
    time: '10 दिन पहले',
    readTime: '4 मिनट',
    image: 'images/articles/enam-online-fasal-bechna-card.webp',
    link: 'articles/enam-online-fasal-bechna'
  },
  {
    id: 'news-23',
    slug: 'madhumakhi-palan-guide',
    title: 'मधुमक्खी पालन (Beekeeping): सरसों व लीची के मौसम में शहद उत्पादन से लाखों की कमाई',
    excerpt: 'राष्ट्रीय मधुमक्खी मिशन (NBHM) के तहत बॉक्स और उपकरणों पर 80% तक सब्सिडी। फसल परागण से उत्पादन में भी वृद्धि।',
    category: 'tech',
    catLabel: 'शहद उत्पादन',
    time: '10 दिन पहले',
    readTime: '5 मिनट',
    image: 'images/articles/madhumakhi-palan-guide-card.webp',
    link: 'articles/madhumakhi-palan-guide'
  },
  {
    id: 'news-24',
    slug: 'murgi-palan-backyard',
    title: 'बैकयार्ड देसी मुर्गी पालन: कड़कनाथ, वनराजा व ग्रामप्रिया से हर हफ्ते नियमित आय',
    excerpt: 'कम जगह और रसोई के बचे खाने पर पलने वाली मुर्गियां। अंडों और देसी मीट की शहरों में भारी मांग।',
    category: 'pashu',
    catLabel: 'कुक्कुट पालन',
    time: '10 दिन पहले',
    readTime: '5 मिनट',
    image: 'images/articles/murgi-palan-backyard-card.webp',
    link: 'articles/murgi-palan-backyard'
  },
  {
    id: 'news-25',
    slug: 'jalbharav-baadh-fasal-bachav',
    title: 'खेत में पानी भरने पर तुरंत क्या करें? पहले 48 घंटे में फसल को सड़ने से बचाने के उपाय',
    excerpt: 'जल निकासी के बाद यूरिया का हल्का छिड़काव, पोटाश का स्प्रे और फंगस से बचाव के लिए कॉपर ऑक्सीक्लोराइड का प्रयोग।',
    category: 'weather',
    catLabel: 'मौसम आपदा',
    time: '12 दिन पहले',
    readTime: '4 मिनट',
    image: 'images/articles/jalbharav-baadh-fasal-bachav-card.webp',
    link: 'articles/jalbharav-baadh-fasal-bachav'
  },
  {
    id: 'news-26',
    slug: 'mirch-kala-thrips',
    title: 'मिर्च में ब्लैक थ्रिप्स (काले कीड़े) का प्रकोप: फूल झड़ने और पत्ती मुड़ने का सटीक इलाज',
    excerpt: 'साउथ इंडिया से उत्तर भारत में फैले नए थ्रिप्स से बचाव। नीले रंग के स्टिकी ट्रैप और अनुशंसित दवाओं की सूची।',
    category: 'crop',
    catLabel: 'कीट नियंत्रण',
    time: '12 दिन पहले',
    readTime: '4 मिनट',
    image: 'images/articles/mirch-kala-thrips-card.webp',
    link: 'articles/mirch-kala-thrips'
  },
  {
    id: 'news-27',
    slug: 'poplar-ki-kheti',
    title: 'पॉपलर की खेती: गेहूं व गन्ने के साथ 5 साल में तैयार पेड़, ₹10-15 लाख तक आय',
    excerpt: 'प्लाईवुड फैक्ट्रियों में भारी मांग वाले पॉपलर के पौधे लगाने का सही समय, दूरी और ईटीपी क्लोन की पहचान।',
    category: 'tech',
    catLabel: 'कृषि वानिकी',
    time: '14 दिन पहले',
    readTime: '5 मिनट',
    image: 'images/articles/poplar-ki-kheti-card.webp',
    link: 'articles/poplar-ki-kheti'
  },
  {
    id: 'news-28',
    slug: 'baingan-tana-phal-chhedak',
    title: 'बैंगन में तना व फल छेदक सूंडी: मुरझाती शाखाएं और कीड़े वाले फलों से मुक्ति',
    excerpt: 'फेरोमोन ट्रैप लगाने की सही विधि और फल तोड़ने के समय सुरक्षित कीटनाशकों का प्रयोग।',
    category: 'crop',
    catLabel: 'सब्जी कीट',
    time: '14 दिन पहले',
    readTime: '4 मिनट',
    image: 'images/articles/baingan-tana-phal-chhedak-card.webp',
    link: 'articles/baingan-tana-phal-chhedak'
  },
  {
    id: 'news-29',
    slug: 'dhan-tana-chhedak',
    title: 'धान में पीला तना छेदक व सफेद बाली: गोभ सूखने से पहले पहचानें और रोकें',
    excerpt: 'समय पर प्रकाश प्रपंच (लाइट ट्रैप) और ट्राइकोकार्ड का उपयोग कर रासायनिक दवाओं के अंधाधुंध खर्च से बचें।',
    category: 'crop',
    catLabel: 'धान कीट',
    time: '15 दिन पहले',
    readTime: '5 मिनट',
    image: 'images/articles/dhan-tana-chhedak-card.webp',
    link: 'articles/dhan-tana-chhedak'
  },
  {
    id: 'news-30',
    slug: 'beej-upchar-vidhi',
    title: 'बीज उपचार (Seed Treatment) का सही क्रम: FIR नियम अपनाकर 20% तक उत्पादन बढ़ाएं',
    excerpt: 'फफूंदनाशी (Fungicide), कीटनाशी (Insecticide) और राइजोबियम जैव उर्वरक (Rhizobium) मिलाने का वैज्ञानिक तरीका।',
    category: 'crop',
    catLabel: 'बीज उपचार',
    time: '15 दिन पहले',
    readTime: '4 मिनट',
    image: 'images/articles/beej-upchar-vidhi-card.webp',
    link: 'articles/beej-upchar-vidhi'
  },
  {
    id: 'news-31',
    slug: 'soyabean-illi-chakra-bhring-mp',
    title: 'सोयाबीन में गर्डल बीटल (चक्र भृंग) व सेमीलूपर इल्ली: एमपी-महाराष्ट्र के लिए गाइड',
    excerpt: 'तना कटने से पहले पत्तियों के छल्लों की पहचान और अनुशंसित कीटनाशक का सही मात्रा में छिड़काव।',
    category: 'crop',
    catLabel: 'सोयाबीन कीट',
    time: '18 दिन पहले',
    readTime: '5 मिनट',
    image: 'images/articles/soyabean-illi-chakra-bhring-mp-card.webp',
    link: 'articles/soyabean-illi-chakra-bhring-mp'
  },
  {
    id: 'news-32',
    slug: 'namo-shetkari-mahasanman-nidhi',
    title: 'नमो शेतकरी महासन्मान निधी: महाराष्ट्र के किसानों को सालाना ₹12,000 की वित्तीय मदद',
    excerpt: 'पीएम किसान के ₹6,000 के अतिरिक्त राज्य सरकार दे रही ₹6,000। पात्रता और आधार लिंकिंग स्टेटस जांचें।',
    category: 'yojana',
    catLabel: 'राज्य योजना',
    time: '18 दिन पहले',
    readTime: '4 मिनट',
    image: 'images/articles/namo-shetkari-mahasanman-nidhi-card.webp',
    link: 'articles/namo-shetkari-mahasanman-nidhi'
  },
  {
    id: 'news-33',
    slug: 'dhan-jivanu-jhulsa-blb',
    title: 'धान में जीवाणु झुलसा (BLB): पत्तियां पीली पड़कर सूखने लगें तो तुरंत करें यह काम',
    excerpt: 'फफूंदनाशी डालने की गलती न करें। कॉपर ऑक्सीक्लोराइड और स्ट्रेप्टोसाइक्लिन का संतुलित मिश्रण ही रोकेगा नुकसान।',
    category: 'crop',
    catLabel: 'धान रोग',
    time: '20 दिन पहले',
    readTime: '4 मिनट',
    image: 'images/articles/dhan-jivanu-jhulsa-blb-card.webp',
    link: 'articles/dhan-jivanu-jhulsa-blb'
  },
  {
    id: 'news-34',
    slug: 'arhar-tur-kheti-guide',
    title: 'अरहर (तुअर) की मेड़ पर बुवाई और निपिंग: शाखाएं बढ़ाकर पाएं 12-15 क्विंटल प्रति एकड़',
    excerpt: 'फूल आने से पहले ऊपरी कलिका तोड़ने से पौधों में ज्यादा फलियां लगती हैं। उकठा रोधी किस्मों का चयन।',
    category: 'crop',
    catLabel: 'दलहन सलाह',
    time: '20 दिन पहले',
    readTime: '5 मिनट',
    image: 'images/articles/arhar-tur-kheti-guide-card.webp',
    link: 'articles/arhar-tur-kheti-guide'
  },
  {
    id: 'news-35',
    slug: 'parali-prabandhan',
    title: 'पराली प्रबंधन: बायो-डीकंपोज़र व सुपर सीडर से बिना आग लगाए गेहूं की सीधी बुवाई',
    excerpt: 'खेत में पराली गलाने से जमीन में 1 क्विंटल पोटाश और नाइट्रोजन जुड़ता है। सरकार द्वारा कस्टम हायरिंग सेंटर से मिलने वाली मशीनें।',
    category: 'tech',
    catLabel: 'पर्यावरण व तकनीक',
    time: '22 दिन पहले',
    readTime: '5 मिनट',
    image: 'images/articles/parali-prabandhan-card.webp',
    link: 'articles/parali-prabandhan'
  },
  {
    id: 'news-36',
    slug: 'prakritik-kheti-jeevamrit',
    title: 'जीवामृत व घनजीवामृत बनाने की विधि: शून्य बजट प्राकृतिक खेती का असली आधार',
    excerpt: 'देशी गाय के गोबर व गोमूत्र से तैयार अमृत खाद। सूक्ष्मजीवों की संख्या लाखों गुना बढ़ाकर मिट्टी को बनाएं उपजाऊ।',
    category: 'khad',
    catLabel: 'जैविक खाद',
    time: '22 दिन पहले',
    readTime: '5 मिनट',
    image: 'images/articles/prakritik-kheti-jeevamrit-card.webp',
    link: 'articles/prakritik-kheti-jeevamrit'
  },
  {
    id: 'news-37',
    slug: 'zinc-ki-kami-fasal',
    title: 'फसलों में जिंक (जस्ता) की कमी के लक्षण: खैरा रोग और पत्तियों का पीलापन तुरंत दूर करें',
    excerpt: 'धान, गेहूं और मक्का में जिंक सल्फेट डालने का सही समय। यूरिया या डीएपी के साथ मिलाने की गलती से बचें।',
    category: 'khad',
    catLabel: 'सूक्ष्म पोषक तत्व',
    time: '25 दिन पहले',
    readTime: '4 मिनट',
    image: 'images/articles/zinc-ki-kami-fasal-card.webp',
    link: 'articles/zinc-ki-kami-fasal'
  },
  {
    id: 'news-38',
    slug: 'sulphur-gandhak-ki-kami',
    title: 'सल्फर (गंधक) का जादू: तिलहनी और दलहनी फसलों में तेल व प्रोटीन की मात्रा बढ़ाएं',
    excerpt: 'सरसों में तेल का प्रतिशत 2 से 3% बढ़ाने के लिए बेंटोनाइट सल्फर का प्रयोग। मिट्टी का पीलापन हटाने में कारगर।',
    category: 'khad',
    catLabel: 'उर्वरक पोषण',
    time: '25 दिन पहले',
    readTime: '4 मिनट',
    image: 'images/articles/sulphur-gandhak-ki-kami-card.webp',
    link: 'articles/sulphur-gandhak-ki-kami'
  },
  {
    id: 'news-39',
    slug: 'kapas-gulabi-sundi',
    title: 'कपास में गुलाबी सुंडी (Pink Bollworm): बंडियों को बर्बाद होने से बचाने का अचूक चक्र',
    excerpt: 'रेफ्यूजिया नॉन-बीटी कतारों का महत्व, फेरोमोन ट्रैप और शुरुआती अवस्था में नीम तेल का छिड़काव।',
    category: 'crop',
    catLabel: 'कपास कीट',
    time: '28 दिन पहले',
    readTime: '5 मिनट',
    image: 'images/articles/kapas-gulabi-sundi-card.webp',
    link: 'articles/kapas-gulabi-sundi'
  },
  {
    id: 'news-40',
    slug: 'machhli-palan-guide',
    title: 'मछली पालन (Fisheries): रोहू, कतला व मृगल कार्प के साथ प्रति एकड़ ₹2-3 लाख की आमदनी',
    excerpt: 'तालाब निर्माण पर प्रधानमंत्री मत्स्य संपदा योजना (PMMSY) के तहत 40-60% सरकारी अनुदान व फिंगरलिंग प्रबंधन।',
    category: 'pashu',
    catLabel: 'मत्स्य पालन',
    time: '1 महीना पहले',
    readTime: '6 मिनट',
    image: 'images/articles/machhli-palan-guide-card.webp',
    link: 'articles/machhli-palan-guide'
  },
  {
    id: 'news-41',
    slug: 'bans-ki-kheti',
    title: 'बांस की खेती (Bamboo Mission): बंजर जमीन पर एक बार लगाएं, 40 साल तक काटें',
    excerpt: 'राष्ट्रीय बांस मिशन के तहत पौधों व ड्रिप पर सब्सिडी। अगरबत्ती, फर्नीचर और कागज उद्योग में सुनिश्चित बाजार।',
    category: 'tech',
    catLabel: 'कृषि वानिकी',
    time: '1 महीना पहले',
    readTime: '5 मिनट',
    image: 'images/articles/bans-ki-kheti-card.webp',
    link: 'articles/bans-ki-kheti'
  },
  {
    id: 'news-42',
    slug: 'chandan-ki-kheti',
    title: 'सफेद चंदन की खेती: कानूनी अनुमति, होस्ट पौधे का चयन और असली बाजार मूल्य',
    excerpt: 'चंदन का पौधा परजीवी होता है, इसलिए कैसुरीना या नीम के साथ लगाएं। 12-15 वर्षों में हार्टवुड का गठन और सुरक्षा नियम।',
    category: 'tech',
    catLabel: 'कीमती पेड़',
    time: '1 महीना पहले',
    readTime: '6 मिनट',
    image: 'images/articles/chandan-ki-kheti-card.webp',
    link: 'articles/chandan-ki-kheti'
  },
  {
    id: 'news-43',
    slug: 'kisan-pehchan-patra-agristack',
    title: 'किसान पहचान पत्र (Farmer ID / AgriStack): हर किसान की बनेगी डिजिटल आईडी',
    excerpt: 'बिना खतौनी और जमीन दस्तावेज दिखाए सीधे बैंक लोन, बीमा क्लेम और खाद सब्सिडी प्राप्त करने की नई व्यवस्था।',
    category: 'yojana',
    catLabel: 'डिजिटल कृषि',
    time: '1 महीना पहले',
    readTime: '4 मिनट',
    image: 'images/articles/kisan-pehchan-patra-agristack-card.webp',
    link: 'articles/kisan-pehchan-patra-agristack'
  },
  {
    id: 'news-44',
    slug: 'vashi-apmc-mandi-guide',
    title: 'वाशी नवी मुंबई APMC मंडी: फलों व सब्जियों के थोक भाव और देश भर से आवक रिपोर्ट',
    excerpt: 'एशिया की सबसे बड़ी कृषि उपज मंडी में किसानों के माल की नीलामी, तुलाई और त्वरित आरटीजीएस भुगतान प्रक्रिया।',
    category: 'mandi',
    catLabel: 'थोक मंडी',
    time: '1 महीना पहले',
    readTime: '5 मिनट',
    image: 'images/articles/vashi-apmc-mandi-guide-card.webp',
    link: 'articles/vashi-apmc-mandi-guide'
  },
  {
    id: 'news-45',
    slug: 'fpo-kisan-utpadak-sangathan',
    title: 'किसान उत्पादक संगठन (FPO): 10 किसान मिलकर बनाएं कंपनी, पाएँ ₹15 लाख सरकारी मदद',
    excerpt: 'थोक में खाद-बीज खरीदने से 25% बचत और सीधे कॉर्पोरेट कंपनियों को अपनी उपज ऊंचे भाव में बेचने का संगठन।',
    category: 'yojana',
    catLabel: 'किसान कंपनी',
    time: '1 महीना पहले',
    readTime: '5 मिनट',
    image: 'images/articles/fpo-kisan-utpadak-sangathan-card.webp',
    link: 'articles/fpo-kisan-utpadak-sangathan'
  }
];
