"""baseline schema

Revision ID: e908133c1e24
Revises: 
Create Date: 2026-07-31 01:12:14.580164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e908133c1e24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('custom', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_tasks_custom'), 'admin_tasks', ['custom'], unique=False)
    op.create_index(op.f('ix_admin_tasks_id'), 'admin_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_admin_tasks_slug'), 'admin_tasks', ['slug'], unique=True)
    op.create_table('kcc_crop_builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('n_qa', sa.Integer(), nullable=True),
    sa.Column('n_seen', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('built_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kcc_crop_builds_crop_key'), 'kcc_crop_builds', ['crop_key'], unique=True)
    op.create_index(op.f('ix_kcc_crop_builds_id'), 'kcc_crop_builds', ['id'], unique=False)
    op.create_index(op.f('ix_kcc_crop_builds_status'), 'kcc_crop_builds', ['status'], unique=False)
    op.create_table('kcc_qa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_key', sa.String(), nullable=False),
    sa.Column('crop', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('ans_key', sa.String(), nullable=True),
    sa.Column('built_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kcc_qa_ans_key'), 'kcc_qa', ['ans_key'], unique=True)
    op.create_index(op.f('ix_kcc_qa_crop_key'), 'kcc_qa', ['crop_key'], unique=False)
    op.create_index(op.f('ix_kcc_qa_id'), 'kcc_qa', ['id'], unique=False)
    op.create_table('lead_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('referer', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_clicks_category'), 'lead_clicks', ['category'], unique=False)
    op.create_index(op.f('ix_lead_clicks_created_at'), 'lead_clicks', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_clicks_district'), 'lead_clicks', ['district'], unique=False)
    op.create_index(op.f('ix_lead_clicks_id'), 'lead_clicks', ['id'], unique=False)
    op.create_index(op.f('ix_lead_clicks_kind'), 'lead_clicks', ['kind'], unique=False)
    op.create_index('ix_lead_clicks_kind_created', 'lead_clicks', ['kind', 'created_at'], unique=False)
    op.create_index(op.f('ix_lead_clicks_target_id'), 'lead_clicks', ['target_id'], unique=False)
    op.create_table('mandi_last_seen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_key', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('variety', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('min_price', sa.String(), nullable=True),
    sa.Column('max_price', sa.String(), nullable=True),
    sa.Column('modal_price', sa.String(), nullable=True),
    sa.Column('arrival_date', sa.String(), nullable=True),
    sa.Column('arrival_dt', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_key')
    )
    op.create_index('mandi_last_seen_csd_idx', 'mandi_last_seen', ['commodity', 'state', 'district'], unique=False)
    op.create_table('mandi_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('variety', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('min_price', sa.String(), nullable=True),
    sa.Column('max_price', sa.String(), nullable=True),
    sa.Column('modal_price', sa.String(), nullable=True),
    sa.Column('arrival_date', sa.String(), nullable=True),
    sa.Column('arrival_dt', sa.Date(), nullable=True),
    sa.Column('group_key', sa.String(), nullable=True),
    sa.Column('row_key', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandi_price_history_arrival_dt'), 'mandi_price_history', ['arrival_dt'], unique=False)
    op.create_index(op.f('ix_mandi_price_history_commodity'), 'mandi_price_history', ['commodity'], unique=False)
    op.create_index(op.f('ix_mandi_price_history_district'), 'mandi_price_history', ['district'], unique=False)
    op.create_index(op.f('ix_mandi_price_history_group_key'), 'mandi_price_history', ['group_key'], unique=False)
    op.create_index(op.f('ix_mandi_price_history_id'), 'mandi_price_history', ['id'], unique=False)
    op.create_index(op.f('ix_mandi_price_history_row_key'), 'mandi_price_history', ['row_key'], unique=True)
    op.create_index(op.f('ix_mandi_price_history_state'), 'mandi_price_history', ['state'], unique=False)
    op.create_table('mandi_price_monthly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('ym', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('median_modal', sa.Integer(), nullable=True),
    sa.Column('min_modal', sa.Integer(), nullable=True),
    sa.Column('max_modal', sa.Integer(), nullable=True),
    sa.Column('n_rows', sa.Integer(), nullable=True),
    sa.Column('slice_key', sa.String(), nullable=True),
    sa.Column('row_key', sa.String(), nullable=True),
    sa.Column('built_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandi_price_monthly_id'), 'mandi_price_monthly', ['id'], unique=False)
    op.create_index(op.f('ix_mandi_price_monthly_row_key'), 'mandi_price_monthly', ['row_key'], unique=True)
    op.create_index(op.f('ix_mandi_price_monthly_slice_key'), 'mandi_price_monthly', ['slice_key'], unique=False)
    op.create_table('mandi_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('variety', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('min_price', sa.String(), nullable=True),
    sa.Column('max_price', sa.String(), nullable=True),
    sa.Column('modal_price', sa.String(), nullable=True),
    sa.Column('prev_modal_price', sa.String(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('spark', sa.String(), nullable=True),
    sa.Column('arrival_date', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandi_prices_commodity'), 'mandi_prices', ['commodity'], unique=False)
    op.create_index(op.f('ix_mandi_prices_district'), 'mandi_prices', ['district'], unique=False)
    op.create_index(op.f('ix_mandi_prices_id'), 'mandi_prices', ['id'], unique=False)
    op.create_index(op.f('ix_mandi_prices_state'), 'mandi_prices', ['state'], unique=False)
    op.create_table('mandi_season_slices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slice_key', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('commodity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('months', sa.Integer(), nullable=True),
    sa.Column('rows_seen', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('built_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandi_season_slices_id'), 'mandi_season_slices', ['id'], unique=False)
    op.create_index(op.f('ix_mandi_season_slices_slice_key'), 'mandi_season_slices', ['slice_key'], unique=True)
    op.create_index(op.f('ix_mandi_season_slices_status'), 'mandi_season_slices', ['status'], unique=False)
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_log_finished_at'), 'sync_log', ['finished_at'], unique=False)
    op.create_index(op.f('ix_sync_log_id'), 'sync_log', ['id'], unique=False)
    op.create_index(op.f('ix_sync_log_source'), 'sync_log', ['source'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('otp', sa.String(), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('primary_crop', sa.String(), nullable=True),
    sa.Column('seller_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('weather_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('weather_condition', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('farming_tip', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_cache_district'), 'weather_cache', ['district'], unique=True)
    op.create_index(op.f('ix_weather_cache_id'), 'weather_cache', ['id'], unique=False)
    op.create_table('weather_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('weather_condition', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('farming_tip', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_history_district'), 'weather_history', ['district'], unique=False)
    op.create_index(op.f('ix_weather_history_fetched_at'), 'weather_history', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_weather_history_id'), 'weather_history', ['id'], unique=False)
    op.create_table('bazar_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='fk_bazar_follows_follower_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name='fk_bazar_follows_following_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='bazar_follow_uidx')
    )
    op.create_index(op.f('ix_bazar_follows_follower_id'), 'bazar_follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_bazar_follows_following_id'), 'bazar_follows', ['following_id'], unique=False)
    op.create_index(op.f('ix_bazar_follows_id'), 'bazar_follows', ['id'], unique=False)
    op.create_table('bazar_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.String(), nullable=False),
    sa.Column('crop', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('crop_slug', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_bazar_posts_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bazar_posts_created_at'), 'bazar_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_bazar_posts_crop'), 'bazar_posts', ['crop'], unique=False)
    op.create_index(op.f('ix_bazar_posts_crop_slug'), 'bazar_posts', ['crop_slug'], unique=False)
    op.create_index(op.f('ix_bazar_posts_district'), 'bazar_posts', ['district'], unique=False)
    op.create_index(op.f('ix_bazar_posts_id'), 'bazar_posts', ['id'], unique=False)
    op.create_index(op.f('ix_bazar_posts_state'), 'bazar_posts', ['state'], unique=False)
    op.create_index(op.f('ix_bazar_posts_status'), 'bazar_posts', ['status'], unique=False)
    op.create_index(op.f('ix_bazar_posts_user_id'), 'bazar_posts', ['user_id'], unique=False)
    op.create_table('carts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_carts_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('crop', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_chat_history_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_table('crop_appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_crop_appeals_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_appeals_commodity'), 'crop_appeals', ['commodity'], unique=False)
    op.create_index(op.f('ix_crop_appeals_created_at'), 'crop_appeals', ['created_at'], unique=False)
    op.create_index(op.f('ix_crop_appeals_district'), 'crop_appeals', ['district'], unique=False)
    op.create_index(op.f('ix_crop_appeals_id'), 'crop_appeals', ['id'], unique=False)
    op.create_index(op.f('ix_crop_appeals_kind'), 'crop_appeals', ['kind'], unique=False)
    op.create_index(op.f('ix_crop_appeals_status'), 'crop_appeals', ['status'], unique=False)
    op.create_index(op.f('ix_crop_appeals_user_id'), 'crop_appeals', ['user_id'], unique=False)
    op.create_table('crop_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crop_key', sa.String(), nullable=False),
    sa.Column('sowing_date', sa.Date(), nullable=False),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('area_unit', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_crop_calendar_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_calendar_id'), 'crop_calendar', ['id'], unique=False)
    op.create_index(op.f('ix_crop_calendar_status'), 'crop_calendar', ['status'], unique=False)
    op.create_index(op.f('ix_crop_calendar_user_id'), 'crop_calendar', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracking_code', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('quote_total', sa.Float(), nullable=True),
    sa.Column('delivery_info', sa.String(), nullable=True),
    sa.Column('dealer_name', sa.String(), nullable=True),
    sa.Column('quote_note', sa.String(), nullable=True),
    sa.Column('quoted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_orders_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_session_id'), 'orders', ['session_id'], unique=False)
    op.create_index(op.f('ix_orders_tracking_code'), 'orders', ['tracking_code'], unique=True)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_push_subscriptions_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_subscriptions_active'), 'push_subscriptions', ['active'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_endpoint'), 'push_subscriptions', ['endpoint'], unique=True)
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('farming_experience', sa.String(), nullable=True),
    sa.Column('family_size', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('tehsil', sa.String(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('pin_code', sa.String(), nullable=True),
    sa.Column('nearest_mandi', sa.String(), nullable=True),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lon', sa.Float(), nullable=True),
    sa.Column('geo_location', sa.String(), nullable=True),
    sa.Column('geo_updated_at', sa.DateTime(), nullable=True),
    sa.Column('farm_size', sa.String(), nullable=True),
    sa.Column('farm_size_unit', sa.String(), nullable=True),
    sa.Column('land_ownership', sa.String(), nullable=True),
    sa.Column('soil_type', sa.String(), nullable=True),
    sa.Column('irrigation_type', sa.String(), nullable=True),
    sa.Column('khasra_number', sa.String(), nullable=True),
    sa.Column('eq_tractor', sa.Boolean(), nullable=True),
    sa.Column('eq_pump', sa.Boolean(), nullable=True),
    sa.Column('eq_thresher', sa.Boolean(), nullable=True),
    sa.Column('eq_sprayer', sa.Boolean(), nullable=True),
    sa.Column('eq_harvester', sa.Boolean(), nullable=True),
    sa.Column('eq_none', sa.Boolean(), nullable=True),
    sa.Column('primary_crop', sa.String(), nullable=True),
    sa.Column('crops_grown', sa.String(), nullable=True),
    sa.Column('farming_season', sa.String(), nullable=True),
    sa.Column('farming_type', sa.String(), nullable=True),
    sa.Column('yield_per_acre', sa.String(), nullable=True),
    sa.Column('crop_problems', sa.Text(), nullable=True),
    sa.Column('pm_kisan_registered', sa.Boolean(), nullable=True),
    sa.Column('has_kcc', sa.Boolean(), nullable=True),
    sa.Column('aadhaar_linked', sa.Boolean(), nullable=True),
    sa.Column('fasal_bima', sa.Boolean(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('annual_income', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('advisory_type', sa.String(), nullable=True),
    sa.Column('special_needs', sa.Text(), nullable=True),
    sa.Column('notif_weather', sa.Boolean(), nullable=True),
    sa.Column('notif_mandi', sa.Boolean(), nullable=True),
    sa.Column('notif_scheme', sa.Boolean(), nullable=True),
    sa.Column('notif_pest', sa.Boolean(), nullable=True),
    sa.Column('notif_tips', sa.Boolean(), nullable=True),
    sa.Column('notif_none', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_profiles_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('bazar_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('offer_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['bazar_posts.id'], name='fk_bazar_comments_post_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_bazar_comments_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bazar_comments_id'), 'bazar_comments', ['id'], unique=False)
    op.create_index(op.f('ix_bazar_comments_post_id'), 'bazar_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_bazar_comments_user_id'), 'bazar_comments', ['user_id'], unique=False)
    op.create_table('bazar_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['bazar_posts.id'], name='fk_bazar_likes_post_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_bazar_likes_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='bazar_like_uidx')
    )
    op.create_index(op.f('ix_bazar_likes_id'), 'bazar_likes', ['id'], unique=False)
    op.create_index(op.f('ix_bazar_likes_post_id'), 'bazar_likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_bazar_likes_user_id'), 'bazar_likes', ['user_id'], unique=False)
    op.create_table('mandi_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_notified_on', sa.Date(), nullable=True),
    sa.Column('last_price', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['push_subscriptions.id'], name='fk_mandi_alerts_subscription_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_mandi_alerts_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'commodity', 'state', 'district', name='uq_mandi_alert_target')
    )
    op.create_index(op.f('ix_mandi_alerts_active'), 'mandi_alerts', ['active'], unique=False)
    op.create_index(op.f('ix_mandi_alerts_commodity'), 'mandi_alerts', ['commodity'], unique=False)
    op.create_index(op.f('ix_mandi_alerts_district'), 'mandi_alerts', ['district'], unique=False)
    op.create_index(op.f('ix_mandi_alerts_id'), 'mandi_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_mandi_alerts_state'), 'mandi_alerts', ['state'], unique=False)
    op.create_index(op.f('ix_mandi_alerts_subscription_id'), 'mandi_alerts', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_mandi_alerts_user_id'), 'mandi_alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mandi_alerts_user_id'), table_name='mandi_alerts')
    op.drop_index(op.f('ix_mandi_alerts_subscription_id'), table_name='mandi_alerts')
    op.drop_index(op.f('ix_mandi_alerts_state'), table_name='mandi_alerts')
    op.drop_index(op.f('ix_mandi_alerts_id'), table_name='mandi_alerts')
    op.drop_index(op.f('ix_mandi_alerts_district'), table_name='mandi_alerts')
    op.drop_index(op.f('ix_mandi_alerts_commodity'), table_name='mandi_alerts')
    op.drop_index(op.f('ix_mandi_alerts_active'), table_name='mandi_alerts')
    op.drop_table('mandi_alerts')
    op.drop_index(op.f('ix_bazar_likes_user_id'), table_name='bazar_likes')
    op.drop_index(op.f('ix_bazar_likes_post_id'), table_name='bazar_likes')
    op.drop_index(op.f('ix_bazar_likes_id'), table_name='bazar_likes')
    op.drop_table('bazar_likes')
    op.drop_index(op.f('ix_bazar_comments_user_id'), table_name='bazar_comments')
    op.drop_index(op.f('ix_bazar_comments_post_id'), table_name='bazar_comments')
    op.drop_index(op.f('ix_bazar_comments_id'), table_name='bazar_comments')
    op.drop_table('bazar_comments')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_endpoint'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_active'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_tracking_code'), table_name='orders')
    op.drop_index(op.f('ix_orders_session_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_crop_calendar_user_id'), table_name='crop_calendar')
    op.drop_index(op.f('ix_crop_calendar_status'), table_name='crop_calendar')
    op.drop_index(op.f('ix_crop_calendar_id'), table_name='crop_calendar')
    op.drop_table('crop_calendar')
    op.drop_index(op.f('ix_crop_appeals_user_id'), table_name='crop_appeals')
    op.drop_index(op.f('ix_crop_appeals_status'), table_name='crop_appeals')
    op.drop_index(op.f('ix_crop_appeals_kind'), table_name='crop_appeals')
    op.drop_index(op.f('ix_crop_appeals_id'), table_name='crop_appeals')
    op.drop_index(op.f('ix_crop_appeals_district'), table_name='crop_appeals')
    op.drop_index(op.f('ix_crop_appeals_created_at'), table_name='crop_appeals')
    op.drop_index(op.f('ix_crop_appeals_commodity'), table_name='crop_appeals')
    op.drop_table('crop_appeals')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_table('carts')
    op.drop_index(op.f('ix_bazar_posts_user_id'), table_name='bazar_posts')
    op.drop_index(op.f('ix_bazar_posts_status'), table_name='bazar_posts')
    op.drop_index(op.f('ix_bazar_posts_state'), table_name='bazar_posts')
    op.drop_index(op.f('ix_bazar_posts_id'), table_name='bazar_posts')
    op.drop_index(op.f('ix_bazar_posts_district'), table_name='bazar_posts')
    op.drop_index(op.f('ix_bazar_posts_crop_slug'), table_name='bazar_posts')
    op.drop_index(op.f('ix_bazar_posts_crop'), table_name='bazar_posts')
    op.drop_index(op.f('ix_bazar_posts_created_at'), table_name='bazar_posts')
    op.drop_table('bazar_posts')
    op.drop_index(op.f('ix_bazar_follows_id'), table_name='bazar_follows')
    op.drop_index(op.f('ix_bazar_follows_following_id'), table_name='bazar_follows')
    op.drop_index(op.f('ix_bazar_follows_follower_id'), table_name='bazar_follows')
    op.drop_table('bazar_follows')
    op.drop_index(op.f('ix_weather_history_id'), table_name='weather_history')
    op.drop_index(op.f('ix_weather_history_fetched_at'), table_name='weather_history')
    op.drop_index(op.f('ix_weather_history_district'), table_name='weather_history')
    op.drop_table('weather_history')
    op.drop_index(op.f('ix_weather_cache_id'), table_name='weather_cache')
    op.drop_index(op.f('ix_weather_cache_district'), table_name='weather_cache')
    op.drop_table('weather_cache')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sync_log_source'), table_name='sync_log')
    op.drop_index(op.f('ix_sync_log_id'), table_name='sync_log')
    op.drop_index(op.f('ix_sync_log_finished_at'), table_name='sync_log')
    op.drop_table('sync_log')
    op.drop_index(op.f('ix_mandi_season_slices_status'), table_name='mandi_season_slices')
    op.drop_index(op.f('ix_mandi_season_slices_slice_key'), table_name='mandi_season_slices')
    op.drop_index(op.f('ix_mandi_season_slices_id'), table_name='mandi_season_slices')
    op.drop_table('mandi_season_slices')
    op.drop_index(op.f('ix_mandi_prices_state'), table_name='mandi_prices')
    op.drop_index(op.f('ix_mandi_prices_id'), table_name='mandi_prices')
    op.drop_index(op.f('ix_mandi_prices_district'), table_name='mandi_prices')
    op.drop_index(op.f('ix_mandi_prices_commodity'), table_name='mandi_prices')
    op.drop_table('mandi_prices')
    op.drop_index(op.f('ix_mandi_price_monthly_slice_key'), table_name='mandi_price_monthly')
    op.drop_index(op.f('ix_mandi_price_monthly_row_key'), table_name='mandi_price_monthly')
    op.drop_index(op.f('ix_mandi_price_monthly_id'), table_name='mandi_price_monthly')
    op.drop_table('mandi_price_monthly')
    op.drop_index(op.f('ix_mandi_price_history_state'), table_name='mandi_price_history')
    op.drop_index(op.f('ix_mandi_price_history_row_key'), table_name='mandi_price_history')
    op.drop_index(op.f('ix_mandi_price_history_id'), table_name='mandi_price_history')
    op.drop_index(op.f('ix_mandi_price_history_group_key'), table_name='mandi_price_history')
    op.drop_index(op.f('ix_mandi_price_history_district'), table_name='mandi_price_history')
    op.drop_index(op.f('ix_mandi_price_history_commodity'), table_name='mandi_price_history')
    op.drop_index(op.f('ix_mandi_price_history_arrival_dt'), table_name='mandi_price_history')
    op.drop_table('mandi_price_history')
    op.drop_index('mandi_last_seen_csd_idx', table_name='mandi_last_seen')
    op.drop_table('mandi_last_seen')
    op.drop_index(op.f('ix_lead_clicks_target_id'), table_name='lead_clicks')
    op.drop_index('ix_lead_clicks_kind_created', table_name='lead_clicks')
    op.drop_index(op.f('ix_lead_clicks_kind'), table_name='lead_clicks')
    op.drop_index(op.f('ix_lead_clicks_id'), table_name='lead_clicks')
    op.drop_index(op.f('ix_lead_clicks_district'), table_name='lead_clicks')
    op.drop_index(op.f('ix_lead_clicks_created_at'), table_name='lead_clicks')
    op.drop_index(op.f('ix_lead_clicks_category'), table_name='lead_clicks')
    op.drop_table('lead_clicks')
    op.drop_index(op.f('ix_kcc_qa_id'), table_name='kcc_qa')
    op.drop_index(op.f('ix_kcc_qa_crop_key'), table_name='kcc_qa')
    op.drop_index(op.f('ix_kcc_qa_ans_key'), table_name='kcc_qa')
    op.drop_table('kcc_qa')
    op.drop_index(op.f('ix_kcc_crop_builds_status'), table_name='kcc_crop_builds')
    op.drop_index(op.f('ix_kcc_crop_builds_id'), table_name='kcc_crop_builds')
    op.drop_index(op.f('ix_kcc_crop_builds_crop_key'), table_name='kcc_crop_builds')
    op.drop_table('kcc_crop_builds')
    op.drop_index(op.f('ix_admin_tasks_slug'), table_name='admin_tasks')
    op.drop_index(op.f('ix_admin_tasks_id'), table_name='admin_tasks')
    op.drop_index(op.f('ix_admin_tasks_custom'), table_name='admin_tasks')
    op.drop_table('admin_tasks')
    # ### end Alembic commands ###
