"""buyers table for the kharidar directory

Backs /bhav/<crop>/<state>/<district>/kharidar. Rows arrive either from the
admin panel or the public /dukan signup form; data/buyers.json stays as the
committed seed and services/buyers.py merges the two.

Why a table rather than writing back to the JSON: Render's free plan has no
persistent disk (no `disk:` block in render.yaml), so a dealer written to
backend/data/buyers.json survives until the next deploy or dyno sleep and then
silently reverts — the failure looks like nothing at all. See db.py::Buyer.

NOTE: production has not been stamped with the baseline yet (docs/BACKLOG.md
§0), and backend/database/db.py::init_db() calls Base.metadata.create_all() on
every boot — so this table will in practice be created by that, not by a
migration run. This revision exists so the migration history stays a truthful
description of the schema for whenever the stamp does happen.

Revision ID: f3d92e4d4a78
Revises: e908133c1e24
Create Date: 2026-07-31 23:27:02.048422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f3d92e4d4a78'
down_revision: Union[str, None] = 'e908133c1e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('commodities', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('since', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyers_active'), 'buyers', ['active'], unique=False)
    op.create_index(op.f('ix_buyers_created_at'), 'buyers', ['created_at'], unique=False)
    op.create_index(op.f('ix_buyers_district'), 'buyers', ['district'], unique=False)
    op.create_index(op.f('ix_buyers_id'), 'buyers', ['id'], unique=False)
    op.create_index(op.f('ix_buyers_slug'), 'buyers', ['slug'], unique=True)
    op.create_index(op.f('ix_buyers_source'), 'buyers', ['source'], unique=False)
    op.create_index(op.f('ix_buyers_status'), 'buyers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buyers_status'), table_name='buyers')
    op.drop_index(op.f('ix_buyers_source'), table_name='buyers')
    op.drop_index(op.f('ix_buyers_slug'), table_name='buyers')
    op.drop_index(op.f('ix_buyers_id'), table_name='buyers')
    op.drop_index(op.f('ix_buyers_district'), table_name='buyers')
    op.drop_index(op.f('ix_buyers_created_at'), table_name='buyers')
    op.drop_index(op.f('ix_buyers_active'), table_name='buyers')
    op.drop_table('buyers')
    # ### end Alembic commands ###
